## STATIC CONFIGURATION
log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  web2:
    address: ":3000"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
