version: '3.1'

services:
  seagull:
    image: tobegit3hub/seagull
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '10086:10086'
  container-web-tty:
    image: wrfly/container-web-tty
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '10085:8080'
  portainer:
    image: portainer/portainer
    volumes:
      - portainer_data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'

volumes:
  portainer_data:
    driver: local